// app-vue/src/components/AddTodo.vue
<template>
    <div class="row justify-content-center">
        <div class="col-10">
            <form @submit.prevent="OnSubmit" >
                <input type="text" v-model="Title">
                <button type="submit" class="btn btn-primary" >Create</button>
            </form>
        </div>
    </div>
</template>

<script lang="ts">
import { TodoModel } from '@/models/todomodel';
import { defineComponent } from "vue"
export default defineComponent({
  name: 'AddTodo',
  components: {
  },
  props: { },
  data() {
      return {Title: "" };
  },
  methods: {
      OnSubmit() {
          if( this.Title.trim() )
          {
              const new_todo = new TodoModel( Date.now(), this.Title, false );
              this.$emit('add-todo', new_todo );
              this.Title = "";
          }
      }
    }  
});
</script>
<style scoped>
button{
    margin-left: 1rem;
}
</style>

// app-angular/src/app/addtodo/addtodo.component.ts
import { Component, EventEmitter, OnInit, Output } from "@angular/core";
import { TodoModel } from "../models/todo.model";

@Component({
    selector: 'addtodo-form',
    templateUrl: './addtodo.component.html',
    styleUrls: ['./addtodo.component.css']
  })
  export class AddTodoComponent implements OnInit {
  
    public Title = "";
    @Output() onCreateTodo = new EventEmitter<TodoModel>();

    ngOnInit(): void {
 
  
    }

    public OnSubmit( event: any ) {

        event.preventDefault();
        this.onCreateTodo.emit( new TodoModel( this.Title ) );
        this.Title = "";
    }
}
<form (ngSubmit)="OnSubmit($event)">
    <input class="col-10" type="text" [(ngModel)]="Title" name="title" placeholder="new todo">
    <button type="submit">Create</button>
</form>
